batch_size: 1
data_dir: ./data/dataset5/
max_length_token: 100
name: eval_bleu
num_epoch: 5
report_step: 100
seed: 1004
vocab_size: 600
wandb: False
mode: 'val' # 'val' or 'test'
model_path: 'model/epoch_9'