batch_size: 16
data_dir: ./data
max_length_token: 100
name: 140k
num_epoch: 5
report_step: 100
seed: 1004
vocab_size: 600
wandb: True
model_path:  microsoft/trocr-small-stage1 # user's pretrained weight or hugginface model name